<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ABJ">

<title>Análise descritiva</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="2-descritiva_files/libs/clipboard/clipboard.min.js"></script>
<script src="2-descritiva_files/libs/quarto-html/quarto.js"></script>
<script src="2-descritiva_files/libs/quarto-html/popper.min.js"></script>
<script src="2-descritiva_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2-descritiva_files/libs/quarto-html/anchor.min.js"></script>
<link href="2-descritiva_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2-descritiva_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2-descritiva_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2-descritiva_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2-descritiva_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="2-descritiva.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise descritiva</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>ABJ </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">22 de maio de 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introdução" class="level1">
<h1>Introdução</h1>
<p>O estudo completo tem como objetivo identificar e analisar as cadeias de lavagem de bens e capitais relacionadas a crimes ambientais. A pesquisa é baseada na sistematização de informações sobre os atores e processos judiciais envolvidos, examinados sob a perspectiva dos crimes ambientais e da atuação jurisdicional no assunto. Ao combinar os temas de crimes ambientais e lavagem de bens e capitais, será possível estudar as sanções previstas nas leis de combate à lavagem de dinheiro, que frequentemente são mais efetivas do que as sanções previstas nas leis de crimes ambientais. Além disso, serão geradas recomendações sobre o assunto.</p>
<p>A pesquisa será desenvolvida a partir de 16 perguntas norteadoras, listadas abaixo.</p>
<ol type="1">
<li>Quais são as atividades que conectam e alimentam a cadeia de fluxos de capitais que promovem o desmatamento?</li>
<li>Quem são os atores envolvidos nos casos de lavagem de dinheiro e corrupção relacionados a crimes ambientais?</li>
<li>Quais são os desafios na diferenciação entre atividades legais e ilegais para fins de identificação de fluxos de lavagem de capitais?</li>
<li>Quais as teses jurídicas de defesa mais utilizadas nas ações envolvendo lavagem de dinheiro, fluxos de capitais para atividades ambientais ilegais e lavagem de dinheiro?</li>
<li>Existem padrões identificáveis nos casos judicializados quanto às circunstâncias, características dos autores, modalidades e tipos de crimes ambientais?</li>
<li>Quais são as decisões tomadas e seus fundamentos jurídicos de fato e a razão de decidir apresentadas nesses casos?</li>
<li>Qual o papel do Poder Judiciário no combate à lavagem de dinheiro e corrupção relacionados a crimes ambientais?</li>
<li>Quais os principais segmentos econômicos ou grupos empresariais que estão envolvidos na cadeia de produção que tenha alguma relação com crime ambiental (indústria de equipamentos pesados, maquinário agrícola, maquinário de mineração, táxi aéreo, bancos e instituições financeiras de fomento agrícola, leasing)?</li>
<li>Como especificar, em caso de crimes ambientais complexos e de grande monta, os mandantes indiretos? Há pessoas jurídicas envolvidas? Há desconsideração de pessoa jurídica nesses casos?</li>
<li>Há normas de ESG (<em>environmental</em>, <em>social</em>, <em>and Governance</em>) que podem reduzir a lavagem de capitais e o fluxo de capitais para atividades ambientais ilegais?</li>
<li>Há atos normativos ou diretrizes no âmbito da Estratégia Nacional de Combate à Corrupção e à Lavagem de Dinheiro - ENCCLA, do Banco Central do Brasil e/ou do Conselho de Controle de Atividades Financeiras - COAF que podem facilitar a identificação de fluxo de capitais em matéria ambiental?</li>
<li>Há correlação entre a incidência de crimes contra a vida ou ameaça em regiões de alta ocorrência de desmatamento, ou mineração ilegal ou crimes ambientais em geral?</li>
<li>Há relação entre a ocorrência da alta incidência de demandas judiciais de conflitos fundiários com crimes ambientais ou crimes contra a vida?</li>
<li>Qual o tempo de duração médio das ações criminais que envolvam a temática ambiental?</li>
<li>Qual a quantidade de ações criminais que apuram crimes contra a vida ou de ameaça contra pessoas ligadas à defesa do meio ambiente ou de movimentos relacionados à proteção de populações indígenas e/ou povos tradicionais que ingressam por ano? Qual o tempo de duração médio dessas ações? Quais as espécies de crime cometidas? Qual a efetividade da identificação da autoria e do cumprimento da pena?</li>
<li>Qual a quantidade de ações criminais que apuram crimes relacionados à questão fundiária que ingressam por ano? Qual o tempo de duração médio dessas ações? Quais as espécies de crime cometidas? Qual a efetividade da identificação da autoria e do cumprimento da pena?</li>
</ol>
<section id="objetivo" class="level2">
<h2 class="anchored" data-anchor-id="objetivo">Objetivo</h2>
<p>O presente relatório tem como objetivo responder às perguntas de pesquisa que podem ser investigadas do ponto de vista empírico-quantitativo. Por se tratar de um levantamento quantitativo, nem todas as questões podem ser endereçadas. Das 16 perguntas listadas acima, 7 foram efetivamente analisadas. Especificamente, as questões 1, 2, 5, 8, 12 e 14.</p>
<p>É importante ressaltar que, na maioria dos casos, não é possível responder às perguntas de forma completa. Por ser um tema que está na intersecção de dois tipos processuais, a identificação dos processos nem sempre é possível, especialmente considerando como fonte as bases de informações básicas, partes e movimentações processuais, como é o caso do DataJud. Ainda assim, as análises podem servir como guia para investigações mais profundas.</p>
</section>
</section>
<section id="bases-de-dados" class="level1">
<h1>Bases de dados</h1>
<p>A análise considera três bases de processos, que chamamos de SireneJud, DataJud e TRF1. Descrevemos as bases de dados a seguir.</p>
<section id="sirenejud" class="level2">
<h2 class="anchored" data-anchor-id="sirenejud">SireneJud</h2>
<p>A base do SireneJud foi fornecida pelo CNJ, a partir de uma extração realizada no dia 26/10/2022. O arquivo foi fornecido no formato CSV, contendo 637.699 linhas e 37 colunas. Diferentes versões da base podem ser acessadas a partir do <a href="https://sirenejud.cnj.jus.br/mapa/geral">link de dados abertos da ferramenta do SireneJud</a>.</p>
<p>A base de dados do SireneJud apresenta uma estrutura comum de bases de dados judiciais, contendo três unidades amostrais distintas: processos, partes e movimentações.</p>
<p>O primeiro passo da análise foi realizar filtros para obter uma base mais próxima do escopo da pesquisa. Infelizmente, a base do SireneJud não permite a realização de filtros que identificam de forma precisa os casos relacionados à lavagem de bens e capitais em crimes ambientais. No entanto, a base auxilia no estudo da dinâmica de crimes ambientais, com diferentes níveis de profundidade.</p>
<p>Os filtros aplicados no momento são:</p>
<ul>
<li>Considerar apenas processos originários no primeiro grau.</li>
<li>Remover processos de alta complexidade.</li>
<li>Remover duplicatas de número de processo (ordenamos por grau antes de tirar as duplicatas).</li>
<li>Remover casos com as classes “Termo Circunstanciado” e “Inquérito Policial”</li>
<li>Considerar apenas processos com origem na Amazônia Legal (AC, AM, RR, AP, PA, MA, TO, RO, MT).</li>
</ul>
<p>Como resultado, a base ficou com 48.717 processos. A base foi utilizada na investigação das questões norteadoras 1, 2, 5, 8, 12 e 14.</p>
</section>
<section id="datajud" class="level2">
<h2 class="anchored" data-anchor-id="datajud">DataJud</h2>
<p>A base do DataJud também foi fornecida pelo CNJ, em dezembro de 2022. A base contém informações de processos relacionados à corrupção e lavagem de dinheiro, que podem ou não estarem ligados a crimes ambientais.</p>
<p>A base de dados do DataJud apresenta uma estrutura similar à do SireneJud, com colunas comuns em bases de dados judiciais, mas agrega todas as informações ao nível de processo. Como efeito, as informações das partes e das movimentações são apresentadas de forma agregada (contagens de eventos ou partes).</p>
<p>A base do DataJud também passou por alguns filtros antes de ser analisada:</p>
<ul>
<li>Considerar apenas processos originários no primeiro grau.</li>
<li>Remover duplicatas de número de processo.</li>
<li>Remover casos com as classes “Termo Circunstanciado” e “Inquérito Policial”.</li>
<li>Remover casos com alguns assuntos relacionados a posse de drogas para uso pessoal, furto e concussão.</li>
<li>Considerar apenas processos com origem nas mesmas unidades jurisdicionais dos processos do SireneJud.</li>
</ul>
<p>Como resultado, a base ficou com 184.879 processos. A base foi utilizada na investigação das questões 1, 2, 5 e 12.</p>
</section>
<section id="trf1" class="level2">
<h2 class="anchored" data-anchor-id="trf1">TRF1</h2>
<p>A base do TRF1 foi obtida via raspagem de dados a partir do banco de decisões do TRF1. Raspagem de dados é um processo de extração de informações de fontes da web, como sites, APIs e arquivos, e armazenamento dos dados coletados em um formato estruturado, como uma planilha ou banco de dados. Esse processo é realizado com o uso de linguagens de programação, que automatizam a extração de dados da web.</p>
<p>A raspagem de dados pode ser usada para coletar dados de várias fontes, sendo uma prática comum para acessar dados que são públicos, mas não são abertos, como é o caso da maior parte dos tribunais brasileiros. É importante destacar que a raspagem de dados só é necessária quando os dados não são abertos: os estudos seriam significativamente facilitados se os tribunais disponibilizassem os dados em formatos eletrônicos legíveis por máquina e não proprietários.</p>
<p>A vantagem da base do TRF1 é que ela é obtida a partir da consulta de palavras-chave nos textos das decisões. Isso permite uma pesquisa mais focada, já que é possível buscar por termos relacionados a questões ambientais juntamente com termos relacionados a lavagem de bens e capitais ou corrupção.</p>
<p>Para construir a base, partimos de algumas palavras-chave envolvendo a temática de crimes ambientais para obter uma lista inicial de processos. A lista foi, então, refinada, para obter informações de processos que se relacionam com corrupção e lavagem de bens e capitais.</p>
<p>Os termos utilizados para captura da primeira lista de processos foram: garimpo, desmatamento, mineração, invasão e grilagem. Os termos foram pesquisados com variações, como existência ou não de acentos e flexões das palavras (por exemplo, garimpo, garimpeiro, etc).</p>
<p>A primeira base obtida dessa forma tinha 32.046 processos. As informações disponíveis são bastante limitadas: o número do processo, o resumo da decisão e o texto da decisão.</p>
<p>A base foi, então, filtrada, com o objetivo de listar casos que podem estar dentro do escopo. Aqui existem duas versões da base: a primeira contém informações de todos os processos envolvendo questões ambientais dentro do recorte temporal e regional da pesquisa, enquanto a segunda contém, além dos recortes anteriores, filtros relacionados à lavagem e corrupção.</p>
<p>A primeira base contém 10.241 processos. A base foi enriquecida com informações da consulta processual (antiga) do TRF1. Os dados também foram obtidos via raspagem de dados, que permitiu a extração de dados como classe, vara, juiz, localização, movimentações e partes. Infelizmente, as partes só estão disponíveis em 2.936 processos.</p>
<p>A segunda base contém apenas 227 processos. Ao aplicar os filtros sobre lavagem e corrupção (especificamente: organização/associação criminosa, quadrilha, lavagem, corrupção, operação), sobram poucos casos a serem considerados.</p>
<p>A base grande do TRF1 foi utilizada para responder às questões 2, 5 e 14. Já a base pequena do TRF1 foi utilizada para responder à questão 1.</p>
</section>
<section id="limitações" class="level2">
<h2 class="anchored" data-anchor-id="limitações">Limitações</h2>
<p>Abaixo, explicamos os motivos de algumas questões não serem investigadas, total ou parcialmente, por conta das limitações das bases de dados. Além disso, mencionamos quais seriam os dados necessários para que as perguntas possam ser respondidas integralmente. É importante que muitas dessas informações não existem de forma estruturada no momento, podendo ser interpretadas como sugestões de melhorias dos dados públicos para utilização em estudos futuros.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 43%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Questão</th>
<th style="text-align: left;">Respondida</th>
<th style="text-align: left;">Bases de dados utilizadas</th>
<th style="text-align: left;">Limitação</th>
<th style="text-align: left;">Base de dados necessária</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Parcialmente</td>
<td style="text-align: left;">sirenejud, datajud, TRF1</td>
<td style="text-align: left;">As atividades só podem ser investigadas através dos assuntos processuais disponíveis.</td>
<td style="text-align: left;">Amostra (ou a totalidade) de petições iniciais de processos envolvendo lavagem de bens e capitais no recorte regional da pesquisa, verificando quais casos envolvem crimes ambientais ou não. Em seguida, levantar, nos casos identificados, as principais atividades envolvidas.</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Parcialmente</td>
<td style="text-align: left;">sirenejud</td>
<td style="text-align: left;">Não é possível filtrar os casos envolvendo lavagem de bens e capitais em crimes ambientais na base do Sirenejud. A base do Datajud disponibilizada não contém informação das partes. A base do TRF1 apresenta informações incompletas de partes e poucos casos dentro do escopo.</td>
<td style="text-align: left;">A partir do filtro realizado para responder à Questão 1, obter as partes relacionadas. Ou seja, ao responder à Questão 1, seria possível responder à Questão 2 somente com os dados do Datajud.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Análise jurídica, não quantitativa</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Análise jurídica, não quantitativa</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Parcialmente</td>
<td style="text-align: left;">Igual à questão 1</td>
<td style="text-align: left;">Igual à Questão 1</td>
<td style="text-align: left;">Igual à Questão 1</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">As bases do Datajud e do Sirenejud não têm informações das sentenças. Na base do TRF1 as sentenças estão disponíveis, mas era inviável extrair as decisões, fundamentos jurídicos e razão de decidir de forma automática.</td>
<td style="text-align: left;">Seria necessário realizar um estudo com classificação manual das peças a partir de amostragem, ou então um estudo de classificação utilizando técnicas de mineração de texto ou ferramentas de inteligência artificial, que estavam fora do escopo da pesquisa</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Análise jurídica, não quantitativa</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Parcialmente</td>
<td style="text-align: left;">Igual à questão 2</td>
<td style="text-align: left;">Igual à Questão 2</td>
<td style="text-align: left;">Igual à Questão 2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Igual à Questão 6</td>
<td style="text-align: left;">Igual à Questão 6, adicionando-se a dificuldade de informações adicionais como desconsideração da personalidade jurídica não são, necessariamente, mencionadas nas decisões. Seria, portanto, necessário analisar as movimentações processuais e outras peças dos processos para obter todas as informações desejadas.</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Análise jurídica, não quantitativa</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Análise jurídica, não quantitativa</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Parcialmente</td>
<td style="text-align: left;">sirenejud, datajud, sinesp</td>
<td style="text-align: left;">A base do SINESP mostra apenas informações sobre crimes contra a vida, não ameaça. Além disso, não é possível filtrar os casos envolvendo lavagen de bens e capitais em crimes ambientais nas bases do Sirenejud e Datajud.</td>
<td style="text-align: left;">Além do filtro realizado para responder à Questão 1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Não é possível filtrar os casos envolvendo conflitos fundiários com crimes ambientais ou crimes contra a vida com os dados disponíveis.</td>
<td style="text-align: left;">Seria necessário que esse assunto estivesse disponível nas Tabelas Processuais Unificadas (TPU). Além disso, os casos envolvendo crimes fundiários devem ser marcados com os assuntos de crime ambiental ou crime contra a vida, quando este for o caso.</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: left;">Sim</td>
<td style="text-align: left;">sirenejud</td>
<td style="text-align: left;">A Questão 14 envolve apenas a análise do tempo médio de duração de ações criminais que envolvem a temática ambiental, sem o recorte de processos envolvendo lavagem de bens e capitais. Portanto, a análise realizada responde à pergunta de forma integral.</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Não é possível filtrar os casos envolvendo crimes contra a vida ou ameaça contra pessoas ligadas à defesa do meio ambiente ou de movimentos relacionados à proteção de populações indígenas e/ou povos tradicionais com os dados disponíveis.</td>
<td style="text-align: left;">Seria necessário que esse assunto estivesse disponível nas Tabelas Processuais Unificadas (TPU).</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Igual à Questão 13</td>
<td style="text-align: left;">Igual à Questão 13</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="dashboard" class="level2">
<h2 class="anchored" data-anchor-id="dashboard">Dashboard</h2>
<p>Para complementar as análises do presente relatório, um <a href="https://abjur.shinyapps.io/ambientalCNJ/">painel de análises estatísticas foi desenvolvido</a>. O painel apresenta informações que reforçam os achados da análise jurimétrica realizada. Por meio dos gráficos específicos disponibilizados no painel, é possível visualizar os dados relacionados aos processos ambientais aplicando filtros. Por exemplo, filtrando pelo TJAM, é possível obter os resultados da pesquisa (assuntos mais comuns, mapa e tempo dos processos) somente para o TJAM, como indicado na figura abaixo.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dashboard1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="assets/img/dashboard1.png" class="img-fluid figure-img" width="818"></p>
<figcaption class="figure-caption">Figura&nbsp;1: Filtro no dashboard da base SirejeJud em processos do TJAM.</figcaption>
</figure>
</div>
</div>
</div>
<p>Outro filtro relevante é o de ano do processo, que permite identificar os padrões (tempo, assuntos, distribuição regional) no período selecionado. Essa informação é útil para compreender a distribuição temporal dos processos e pode auxiliar na identificação de períodos mais críticos. Ao relacionar esses dados com as respostas da análise descritiva, é possível fortalecer as conclusões sobre a distribuição dos processos e a atuação do sistema jurídico em diferentes localidades.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dashboard2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="assets/img/dashboard2.png" class="img-fluid figure-img" width="816"></p>
<figcaption class="figure-caption">Figura&nbsp;2: Filtro no dashboard da base SirejeJud em processos entre 2011 e 2015.</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análises" class="level1">
<h1>Análises</h1>
<p>A seguir, apresentamos investigações sobre as questões norteadoras. Cada subseção é de uma das questões. As investigações mostram os resultados principais da análise descritiva.</p>
<section id="questão-1" class="level2">
<h2 class="anchored" data-anchor-id="questão-1">Questão 1</h2>
<p><strong>Questão</strong>: Quais são as atividades que conectam e alimentam a cadeia de fluxos de capitais que promovem o desmatamento?</p>
<section id="sirenejud-1" class="level3">
<h3 class="anchored" data-anchor-id="sirenejud-1">SireneJud</h3>
<p>O SireneJud oferece informações limitadas sobre essa questão. As informações disponíveis na base que podem trazer insumos são os assuntos dos processos e a localização dos processos.</p>
<p>Do total de 48717 processos, 38848 (80%) são estaduais. Dentre os processos estaduais, o tribunal mais comum é o TJMT, com 12665 (32.6%) dos processos estaduais.</p>
<p>As 10 classes mais comuns dos processos estão na <a href="#tbl-classe">Tabela&nbsp;1</a>. A classe com maior volume de processos é a ação civil pública. Essa classe geralmente não é a mais frequente em análises de processos, sendo uma característica específica desta base de dados.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-classe" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;1: Dez classes mais comuns.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Classe</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ação Civil Pública</td>
<td style="text-align: right;">11384</td>
<td style="text-align: right;">23.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ação Penal - Procedimento Ordinário</td>
<td style="text-align: right;">9306</td>
<td style="text-align: right;">19.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Procedimento Comum Cível</td>
<td style="text-align: right;">8948</td>
<td style="text-align: right;">18.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crimes Ambientais</td>
<td style="text-align: right;">4380</td>
<td style="text-align: right;">9.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execução Fiscal</td>
<td style="text-align: right;">2055</td>
<td style="text-align: right;">4.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ação Penal - Procedimento Sumário</td>
<td style="text-align: right;">1729</td>
<td style="text-align: right;">3.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumprimento de sentença</td>
<td style="text-align: right;">1295</td>
<td style="text-align: right;">2.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Execução da Pena</td>
<td style="text-align: right;">1240</td>
<td style="text-align: right;">2.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Auto de Prisão em Flagrante</td>
<td style="text-align: right;">1218</td>
<td style="text-align: right;">2.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ação Penal - Procedimento Sumaríssimo</td>
<td style="text-align: right;">1206</td>
<td style="text-align: right;">2.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">5956</td>
<td style="text-align: right;">12.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">48717</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Os 10 assuntos mais comuns estão na <a href="#tbl-assunto">Tabela&nbsp;2</a>. É possível notar que assuntos genéricos como “Dano Ambiental” e “Flora” estão bastante presentes nos dados. Por isso, é difícil medir quais são as atividades que conectam e alimentam a cadeia de fluxos de capitais que promovem o desmatamento apenas com essa informação.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-assunto" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;2: Dez assuntos mais comuns. Um processo pode ter mais de um assunto.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Assunto</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dano Ambiental</td>
<td style="text-align: right;">14780</td>
<td style="text-align: right;">28.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crimes contra a Flora</td>
<td style="text-align: right;">8803</td>
<td style="text-align: right;">16.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crimes contra o Meio Ambiente e o Patrimônio Genético</td>
<td style="text-align: right;">6268</td>
<td style="text-align: right;">11.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Revogação/Anulação de multa ambiental</td>
<td style="text-align: right;">4343</td>
<td style="text-align: right;">8.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Da Poluição</td>
<td style="text-align: right;">3202</td>
<td style="text-align: right;">6.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flora</td>
<td style="text-align: right;">2686</td>
<td style="text-align: right;">5.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Indenização por Dano Ambiental</td>
<td style="text-align: right;">2628</td>
<td style="text-align: right;">5.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crimes contra a Fauna</td>
<td style="text-align: right;">2108</td>
<td style="text-align: right;">4.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Revogação/Concessão de Licença Ambiental</td>
<td style="text-align: right;">1615</td>
<td style="text-align: right;">3.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pesca</td>
<td style="text-align: right;">1429</td>
<td style="text-align: right;">2.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">4713</td>
<td style="text-align: right;">9.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">52575</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#fig-mapa">Figura&nbsp;3</a> mostra os pontos em que os processos foram distribuídos. Os pontos fora da área demarcada indicam processos do Maranhão que estão fora da Amazônia Legal. Os cinco municípios com mais processos são: Cuiabá, Porto Velho, Belém, Manaus e Altamira.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mapa" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-mapa-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;3: Pontos de distribuição dos processos</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#tbl-municipios">Tabela&nbsp;3</a> mostra os 10 municípios com mais processos. A maioria são capitais, o que é esperado, já que são municípios mais populosos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-municipios" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;3: Municípios com mais processos.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cuiaba / MT</td>
<td style="text-align: right;">5161</td>
<td style="text-align: right;">10.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Porto Velho / RO</td>
<td style="text-align: right;">3833</td>
<td style="text-align: right;">7.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manaus / AM</td>
<td style="text-align: right;">3323</td>
<td style="text-align: right;">6.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Barcarena / PA</td>
<td style="text-align: right;">2069</td>
<td style="text-align: right;">4.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Altamira / PA</td>
<td style="text-align: right;">1926</td>
<td style="text-align: right;">4.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Belem / PA</td>
<td style="text-align: right;">1513</td>
<td style="text-align: right;">3.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boa Vista / RR</td>
<td style="text-align: right;">1322</td>
<td style="text-align: right;">2.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sinop / MT</td>
<td style="text-align: right;">1119</td>
<td style="text-align: right;">2.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Itaituba / PA</td>
<td style="text-align: right;">1053</td>
<td style="text-align: right;">2.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sao Luis / MA</td>
<td style="text-align: right;">979</td>
<td style="text-align: right;">2.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">26419</td>
<td style="text-align: right;">54.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">48717</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-ilg">Tabela&nbsp;4</a> mostra os municípios com maior litigiosidade (processos por 100 mil habitantes). É possível identificar que vários municípios pequenos (com menos de 10 mil habitantes) figuram entre os mais litigiosos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ilg" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;4: Municípios com mais litigiosidade, considerando população do Censo IBGE de 2010.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">ILG</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Claudia / MT</td>
<td style="text-align: right;">396</td>
<td style="text-align: right;">3670.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nova Ubirata / MT</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">3018.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Itauba / MT</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">2899.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Feliz Natal / MT</td>
<td style="text-align: right;">298</td>
<td style="text-align: right;">2762.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cristalandia / TO</td>
<td style="text-align: right;">151</td>
<td style="text-align: right;">2174.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Barcarena / PA</td>
<td style="text-align: right;">2069</td>
<td style="text-align: right;">2116.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Altamira / PA</td>
<td style="text-align: right;">1926</td>
<td style="text-align: right;">2065.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marcelandia / MT</td>
<td style="text-align: right;">194</td>
<td style="text-align: right;">1663.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colniza / MT</td>
<td style="text-align: right;">344</td>
<td style="text-align: right;">1472.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Comodoro / MT</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">1337.4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-ilg-50k">Tabela&nbsp;5</a> mostra os municípios com maior litigiosidade, considerando somente municípios com mais de 50 mil habitantes. Novamente aparecem algumas capitais e figuram entre os mais litigiosos o município de Altamira, que é o município com maior área no país.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ilg-50k" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;5: Municípios com mais litigiosidade.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Processos/100k hab.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Barcarena / PA</td>
<td style="text-align: right;">2069</td>
<td style="text-align: right;">2116.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Altamira / PA</td>
<td style="text-align: right;">1926</td>
<td style="text-align: right;">2065.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Itaituba / PA</td>
<td style="text-align: right;">1053</td>
<td style="text-align: right;">1134.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sinop / MT</td>
<td style="text-align: right;">1119</td>
<td style="text-align: right;">999.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cuiaba / MT</td>
<td style="text-align: right;">5161</td>
<td style="text-align: right;">943.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Porto Velho / RO</td>
<td style="text-align: right;">3833</td>
<td style="text-align: right;">914.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sao Felix Do Xingu / PA</td>
<td style="text-align: right;">674</td>
<td style="text-align: right;">882.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Breu Branco / PA</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">693.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sorriso / MT</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">547.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rondonopolis / MT</td>
<td style="text-align: right;">954</td>
<td style="text-align: right;">494.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A análise anterior sugere que seja realizado de quantidade de processos por 1000km² de área do município. A <a href="#tbl-ila-50k">Tabela&nbsp;6</a> mostra os municípios com maior litigiosidade por área, considerando somente municípios com mais de 5000 km² de área. Novamente aparecem algumas capitais e figura entre os mais litigiosos o município de Cuiabá.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ila-50k" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;6: Municípios com maiores taxas de processos por mil quilômetros quadrados.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Processos/1000 km²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cuiaba / MT</td>
<td style="text-align: right;">5161</td>
<td style="text-align: right;">1016.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manaus / AM</td>
<td style="text-align: right;">3323</td>
<td style="text-align: right;">291.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boa Vista / RR</td>
<td style="text-align: right;">1322</td>
<td style="text-align: right;">232.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Macapa / AP</td>
<td style="text-align: right;">827</td>
<td style="text-align: right;">126.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Porto Velho / RO</td>
<td style="text-align: right;">3833</td>
<td style="text-align: right;">112.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maraba / PA</td>
<td style="text-align: right;">840</td>
<td style="text-align: right;">55.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rio Branco / AC</td>
<td style="text-align: right;">409</td>
<td style="text-align: right;">46.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santarem / PA</td>
<td style="text-align: right;">710</td>
<td style="text-align: right;">39.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sorriso / MT</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">38.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ulianopolis / PA</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">38.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Uma análise de interesse é correlacionar a litigiosidade com o desmatamento. Para isso, foi obtida uma base do sistema PRODES, de onde é possível calcular o percentual de área desmatada com relação à área total do município. Tais dados foram confrontados com o índice de litigiosidade (casos novos por 100.000 habitantes). O resultado é a <a href="#fig-ilg-desmatamento-sirenejud">Figura&nbsp;4</a>, mostrando que as quantidades não são correlacionadas.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ilg-desmatamento-sirenejud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-ilg-desmatamento-sirenejud-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;4: Gráfico de dispersão mostrando a relação entre a litigiosidade e o percentual de desmatamento do município.</figcaption>
</figure>
</div>
</div>
</div>
<section id="segundo-grau" class="level4">
<h4 class="anchored" data-anchor-id="segundo-grau">Segundo grau</h4>
<p>Abaixo, repetimos algumas análises considerando a base do segundo grau do SireneJud. A base foi construída utilizando os mesmos filtros que a base do primeiro grau, moficiando apenas o filtro da instância.</p>
<p>Do total de 6434 processos, 6434 (100%) são estaduais. Dentre os processos estaduais, o tribunal mais comum é o TJPA, com 2420 (37.6%) dos processos estaduais.</p>
<p>As 10 classes mais comuns dos processos estão na <a href="#tbl-classe-2grau">Tabela&nbsp;7</a>. A classe com maior volume de processos é a apelação cível, seguida por agravos de instrumento. As classes fazem sentido, considerando que o segundo grau costuma ser formado basicamente de apelações e agravos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-classe-2grau" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;7: Dez classes mais comuns no segundo grau.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Classe</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Apelação Cível</td>
<td style="text-align: right;">3706</td>
<td style="text-align: right;">57.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agravo de Instrumento</td>
<td style="text-align: right;">1399</td>
<td style="text-align: right;">21.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Apelação Criminal</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">4.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remessa Necessária Cível</td>
<td style="text-align: right;">246</td>
<td style="text-align: right;">3.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recurso Especial</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">2.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Habeas Corpus Criminal</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">1.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Apelação / Remessa Necessária</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">1.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mandado de Segurança Cível</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">1.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recurso em Sentido Estrito</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">1.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conflito de competência cível</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">213</td>
<td style="text-align: right;">3.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">6434</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Os 10 assuntos mais comuns estão na <a href="#tbl-assunto-2grau">Tabela&nbsp;8</a>. É possível notar que assuntos genéricos como “Dano Ambiental” continuam bastante presentes nos dados. Por isso, é difícil medir quais são as atividades que conectam e alimentam a cadeia de fluxos de capitais que promovem o desmatamento apenas com essa informação.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-assunto-2grau" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;8: Dez assuntos mais comuns no segundo grau. Um processo pode ter mais de um assunto.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Assunto</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dano Ambiental</td>
<td style="text-align: right;">3571</td>
<td style="text-align: right;">47.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indenização por Dano Ambiental</td>
<td style="text-align: right;">927</td>
<td style="text-align: right;">12.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Revogação/Anulação de multa ambiental</td>
<td style="text-align: right;">572</td>
<td style="text-align: right;">7.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Revogação/Concessão de Licença Ambiental</td>
<td style="text-align: right;">468</td>
<td style="text-align: right;">6.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flora</td>
<td style="text-align: right;">459</td>
<td style="text-align: right;">6.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">DIREITO AMBIENTAL</td>
<td style="text-align: right;">224</td>
<td style="text-align: right;">3.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crimes contra a Flora</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">2.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Área de Preservação Permanente</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">2.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Da Poluição</td>
<td style="text-align: right;">172</td>
<td style="text-align: right;">2.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Poluição</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">1.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">619</td>
<td style="text-align: right;">8.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">7523</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-tribunais-2grau">Tabela&nbsp;9</a> mostra os tribunais que mais aparecem no segundo grau. Pará e Mato Grosso figuram entre os mais frequentes.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tribunais-2grau" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;9: Tribunais mais comuns nos processos de segundo grau.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PA</td>
<td style="text-align: right;">2420</td>
<td style="text-align: right;">37.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MT</td>
<td style="text-align: right;">1944</td>
<td style="text-align: right;">30.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RO</td>
<td style="text-align: right;">1206</td>
<td style="text-align: right;">18.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">TO</td>
<td style="text-align: right;">288</td>
<td style="text-align: right;">4.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AM</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">3.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">RR</td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">2.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">1.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">AP</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">1.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AC</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">0.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">6434</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="datajud-1" class="level3">
<h3 class="anchored" data-anchor-id="datajud-1">DataJud</h3>
<p>Com relação ao DataJud, a única análise de interesse é nos assuntos dos processos. Ainda assim, a análise é bastante limitada, já que não possui o filtro de processos ambientais. Pode-se dizer, apenas, que nas regiões estudadas esses são os tipos de processos mais comuns.</p>
<p>A <a href="#tbl-assuntos-datajud">Tabela&nbsp;10</a> mostra os assuntos mais comuns dos processos. É possível notar que assuntos relacionados a tráfico de drogas são os mais frequentes, seguidos de peculato e quadrilha/bando.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-assuntos-datajud" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;10: Assuntos com mais processos.</caption>
<colgroup>
<col style="width: 86%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assunto</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Tráfico de Drogas e Condutas Afins</td>
<td style="text-align: right;">122987</td>
<td style="text-align: right;">66.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Associação para a Produção e Tráfico e Condutas Afins</td>
<td style="text-align: right;">15487</td>
<td style="text-align: right;">8.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crimes de Tráfico Ilícito e Uso Indevido de Drogas</td>
<td style="text-align: right;">11223</td>
<td style="text-align: right;">6.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peculato</td>
<td style="text-align: right;">4412</td>
<td style="text-align: right;">2.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Quadrilha ou Bando</td>
<td style="text-align: right;">4019</td>
<td style="text-align: right;">2.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colaboração com Grupo, Organização ou Associação Destinados à Produção ou Tráfico de Drogas</td>
<td style="text-align: right;">2916</td>
<td style="text-align: right;">1.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Contrabando ou descaminho</td>
<td style="text-align: right;">2269</td>
<td style="text-align: right;">1.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Corrupção ativa</td>
<td style="text-align: right;">1893</td>
<td style="text-align: right;">1.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crimes do Sistema Nacional de Armas</td>
<td style="text-align: right;">1608</td>
<td style="text-align: right;">0.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Promoção, constituição, financiamento ou integração de Organização Criminosa</td>
<td style="text-align: right;">1275</td>
<td style="text-align: right;">0.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">14483</td>
<td style="text-align: right;">7.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(vazio)</td>
<td style="text-align: right;">1192</td>
<td style="text-align: right;">0.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">183764</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#fig-mapa-datajud">Figura&nbsp;5</a> mostra os pontos em que os processos foram distribuídos. Os pontos fora da área demarcada indicam processos do Maranhão que estão fora da Amazônia Legal. Os cinco municípios com mais processos são: Belém, Boa Vista, São Luís, Rio Branco e Manaus.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mapa-datajud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-mapa-datajud-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;5: Pontos de distribuição dos processos</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#tbl-municipios-datajud">Tabela&nbsp;11</a> mostra os 10 municípios com mais processos. A maioria são capitais, o que é esperado, já que são municípios mais populosos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-municipios-datajud" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;11: Municípios com mais processos.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Belém / Pará</td>
<td style="text-align: right;">14435</td>
<td style="text-align: right;">7.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boa Vista / Roraima</td>
<td style="text-align: right;">8573</td>
<td style="text-align: right;">4.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">São Luís / Maranhão</td>
<td style="text-align: right;">8015</td>
<td style="text-align: right;">4.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rio Branco / Acre</td>
<td style="text-align: right;">6608</td>
<td style="text-align: right;">3.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manaus / Amazônas</td>
<td style="text-align: right;">5307</td>
<td style="text-align: right;">2.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santarém / Pará</td>
<td style="text-align: right;">4161</td>
<td style="text-align: right;">2.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ananindeua / Pará</td>
<td style="text-align: right;">3714</td>
<td style="text-align: right;">2.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cuiabá / Mato Grosso</td>
<td style="text-align: right;">3282</td>
<td style="text-align: right;">1.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Castanhal / Pará</td>
<td style="text-align: right;">2671</td>
<td style="text-align: right;">1.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Macapá / Amapá</td>
<td style="text-align: right;">2615</td>
<td style="text-align: right;">1.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">124383</td>
<td style="text-align: right;">67.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">183764</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-ilg-datajud">Tabela&nbsp;12</a> mostra os municípios com maior litigiosidade (processos por 100 mil habitantes). É possível identificar que vários municípios pequenos (com menos de 10 mil habitantes) figuram entre os mais litigiosos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ilg-datajud" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;12: Municípios com mais litigiosidade. Considerada população do Censo IBGE de 2010.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">ILG</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Santarém Novo / Pará</td>
<td style="text-align: right;">437</td>
<td style="text-align: right;">7684.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cristalândia / Tocantins</td>
<td style="text-align: right;">477</td>
<td style="text-align: right;">6870.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Filadélfia / Tocantins</td>
<td style="text-align: right;">477</td>
<td style="text-align: right;">5924.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pedro Afonso / Tocantins</td>
<td style="text-align: right;">547</td>
<td style="text-align: right;">4804.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Itaguatins / Tocantins</td>
<td style="text-align: right;">233</td>
<td style="text-align: right;">4051.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Miracema Do Tocantins / Tocantins</td>
<td style="text-align: right;">797</td>
<td style="text-align: right;">3904.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manoel Urbano / Acre</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">3770.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Salinópolis / Pará</td>
<td style="text-align: right;">1268</td>
<td style="text-align: right;">3456.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Augustinópolis / Tocantins</td>
<td style="text-align: right;">539</td>
<td style="text-align: right;">3432.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">São Luiz / Roraima</td>
<td style="text-align: right;">208</td>
<td style="text-align: right;">3251.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-ilg-50k-datajud">Tabela&nbsp;13</a> mostra os municípios com maior litigiosidade, considerando somente municípios com mais de 50 mil habitantes. Novamente aparecem algumas capitais e figuram entre os mais litigiosos o município de Cáceres/MT.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ilg-50k-datajud" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;13: Municípios com mais litigiosidade.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Processos/100k hab.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Boa Vista / Roraima</td>
<td style="text-align: right;">8573</td>
<td style="text-align: right;">3054.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Benevides / Pará</td>
<td style="text-align: right;">1274</td>
<td style="text-align: right;">2505.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Santa Izabel Do Pará / Pará</td>
<td style="text-align: right;">1200</td>
<td style="text-align: right;">2141.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bragança / Pará</td>
<td style="text-align: right;">2295</td>
<td style="text-align: right;">2094.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rio Branco / Acre</td>
<td style="text-align: right;">6608</td>
<td style="text-align: right;">2010.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gurupi / Tocantins</td>
<td style="text-align: right;">1328</td>
<td style="text-align: right;">1743.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Castanhal / Pará</td>
<td style="text-align: right;">2671</td>
<td style="text-align: right;">1566.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Redenção / Pará</td>
<td style="text-align: right;">1076</td>
<td style="text-align: right;">1471.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Santarém / Pará</td>
<td style="text-align: right;">4161</td>
<td style="text-align: right;">1452.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cáceres / Mato Grosso</td>
<td style="text-align: right;">1230</td>
<td style="text-align: right;">1430.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-ila-50k-datajud">Tabela&nbsp;14</a> mostra os municípios com maior litigiosidade por área, considerando somente municípios com mais de 5000 km² de área. Novamente aparecem algumas capitais e figura entre os mais litigiosos o município de Cuiabá.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ila-50k-datajud" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;14: Municípios com maiores taxas de processos por mil quilômetros quadrados.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Município/UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Processos/1000 km²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Boa Vista</td>
<td style="text-align: right;">8573</td>
<td style="text-align: right;">1507.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rio Branco</td>
<td style="text-align: right;">6608</td>
<td style="text-align: right;">747.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cuiabá</td>
<td style="text-align: right;">3282</td>
<td style="text-align: right;">646.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manaus</td>
<td style="text-align: right;">5307</td>
<td style="text-align: right;">465.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Macapá</td>
<td style="text-align: right;">2615</td>
<td style="text-align: right;">398.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santarém</td>
<td style="text-align: right;">4161</td>
<td style="text-align: right;">232.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parauapebas</td>
<td style="text-align: right;">1588</td>
<td style="text-align: right;">230.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Açailândia</td>
<td style="text-align: right;">1035</td>
<td style="text-align: right;">178.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ji-Paraná</td>
<td style="text-align: right;">1100</td>
<td style="text-align: right;">159.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manacapuru</td>
<td style="text-align: right;">1089</td>
<td style="text-align: right;">148.4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Uma análise de interesse é correlacionar a litigiosidade com o desmatamento. Para isso, foi obtida uma base do sistema PRODES, de onde é possível calcular o percentual de área desmatada com relação à área total do município. O resultado é a <a href="#fig-ilg-desmatamento-datajud">Figura&nbsp;6</a>, que mostra que as quantidades não são correlacionadas.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ilg-desmatamento-datajud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-ilg-desmatamento-datajud-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;6: Gráfico de dispersão mostrando a relação entre a litigiosidade e o percentual de desmatamento do município.</figcaption>
</figure>
</div>
</div>
</div>
<section id="segundo-grau-1" class="level4">
<h4 class="anchored" data-anchor-id="segundo-grau-1">Segundo grau</h4>
<p>Abaixo, repetimos algumas análises considerando a base do segundo grau do DataJud. A base foi construída utilizando os mesmos filtros que a base do primeiro grau, moficiando apenas o filtro da instância.</p>
<p>Os 10 assuntos mais comuns estão na <a href="#tbl-assunto-datajud-2grau">Tabela&nbsp;15</a>. Assuntos relacionados a tráfico de drogas são os mais frequentes, seguidos de quadrilha ou bando, mas com um percentual bem menor.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-assunto-datajud-2grau" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;15: Dez assuntos mais comuns no segundo grau. Um processo pode ter mais de um assunto.</caption>
<colgroup>
<col style="width: 87%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assunto</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Tráfico de Drogas e Condutas Afins</td>
<td style="text-align: right;">33773</td>
<td style="text-align: right;">66.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Associação para a Produção e Tráfico e Condutas Afins</td>
<td style="text-align: right;">6168</td>
<td style="text-align: right;">12.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crimes de Tráfico Ilícito e Uso Indevido de Drogas</td>
<td style="text-align: right;">2335</td>
<td style="text-align: right;">4.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colaboração com Grupo, Organização ou Associação Destinados à Produção ou Tráfico de Drogas</td>
<td style="text-align: right;">1075</td>
<td style="text-align: right;">2.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Quadrilha ou Bando</td>
<td style="text-align: right;">948</td>
<td style="text-align: right;">1.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peculato</td>
<td style="text-align: right;">781</td>
<td style="text-align: right;">1.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Habeas Corpus - Cabimento</td>
<td style="text-align: right;">635</td>
<td style="text-align: right;">1.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Promoção, constituição, financiamento ou integração de Organização Criminosa</td>
<td style="text-align: right;">523</td>
<td style="text-align: right;">1.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crimes do Sistema Nacional de Armas</td>
<td style="text-align: right;">411</td>
<td style="text-align: right;">0.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prisão Preventiva</td>
<td style="text-align: right;">405</td>
<td style="text-align: right;">0.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">4151</td>
<td style="text-align: right;">8.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">51205</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-tribunais-datajud-2grau">Tabela&nbsp;16</a> mostra os tribunais que mais aparecem no segundo grau. Assim como no SireneJud, Pará e Mato Grosso figuram entre os mais frequentes.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tribunais-datajud-2grau" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;16: Tribunais mais comuns nos processos de segundo grau.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">UF</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PA</td>
<td style="text-align: right;">15924</td>
<td style="text-align: right;">31.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MT</td>
<td style="text-align: right;">9632</td>
<td style="text-align: right;">18.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TO</td>
<td style="text-align: right;">6164</td>
<td style="text-align: right;">12.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">AC</td>
<td style="text-align: right;">5254</td>
<td style="text-align: right;">10.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA</td>
<td style="text-align: right;">4791</td>
<td style="text-align: right;">9.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">RO</td>
<td style="text-align: right;">3894</td>
<td style="text-align: right;">7.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AM</td>
<td style="text-align: right;">2858</td>
<td style="text-align: right;">5.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">RR</td>
<td style="text-align: right;">2387</td>
<td style="text-align: right;">4.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AP</td>
<td style="text-align: right;">301</td>
<td style="text-align: right;">0.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">51205</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="trf1-1" class="level3">
<h3 class="anchored" data-anchor-id="trf1-1">TRF1</h3>
<p>A análise no TRF1 foi baseada na quantidade e proporção de casos que apareceram nas consultas de processos. Apesar de ser mais curta, a análise pode dar informações um pouco mais relevantes do que as análises anteriores, que se baseiam apenas em estatísticas gerais.</p>
<p>A <a href="#tbl-tema-trf1">Tabela&nbsp;17</a> mostra as atividades com maior volume processual na base pequena do TRF1. É possível notar que o desmatamento é a atividade que mais aparece na consulta, seguida por garimpo.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tema-trf1" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;17: Atividades com maior volume processual no TRF1.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Tema</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Desmatamento</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">44.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Garimpo</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">39.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Invasão</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">11.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grilagem</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mineração</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">227</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="discussão" class="level3">
<h3 class="anchored" data-anchor-id="discussão">Discussão</h3>
<p>As análises mostradas acima são apenas um guia para responder à questão norteadora. Os resultados indicam que a atividade mais comum é o desmatamento, seguida pelo garimpo. Além disso, as análises do DataJud e SireneJud, apesar de limitadas, mostram regiões e assuntos processuais que podem estar relacionados ao tema de interesse.</p>
</section>
</section>
<section id="questão-2" class="level2">
<h2 class="anchored" data-anchor-id="questão-2">Questão 2</h2>
<p><strong>Questão</strong>: Quem são os atores envolvidos nos casos de lavagem de dinheiro e corrupção relacionados a crimes ambientais?</p>
<section id="sirenejud-2" class="level3">
<h3 class="anchored" data-anchor-id="sirenejud-2">SireneJud</h3>
<p>A <a href="#tbl-tipo-pessoa">Tabela&nbsp;18</a> mostra os tipos de pessoas que estão no polo passivo. A maior parte é de pessoas físicas, sendo que quase 2% da base possui autoridades, órgão de representação ou valores vazios.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tipo-pessoa" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;18: Tipos de pessoas</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo de pessoa</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FISICA</td>
<td style="text-align: right;">70550</td>
<td style="text-align: right;">66.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">JURIDICA</td>
<td style="text-align: right;">33656</td>
<td style="text-align: right;">31.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AUTORIDADE</td>
<td style="text-align: right;">1577</td>
<td style="text-align: right;">1.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ORGAOREPRESENTACAO</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">0.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">105929</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Vamos analisar apenas as pessoas jurídicas. Dentre as partes, aproximadamente 4% têm CNPJ vazio e 96% preenchido. No total, são cerca de 8000 CNPJs distintos e com 14 dígitos, que foram pesquisados na base de dados abertos da Receita Federal do Brasil (RFB). Quase a totalidade (99%) foram encontrados. Alguns resultados disso foram colocados a seguir.</p>
<p>A <a href="#tbl-litigantes-passivo">Tabela&nbsp;19</a> mostra os quinze maiores litigantes no polo passivo. O nome que mais aparece é o vazio, que são casos em que o campo do CNPJ está vazio. Outros nomes da lista não fazem muito sentido estarem no polo passivo. Das empresas privadas, destacam-se as empresas de energia.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-litigantes-passivo" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;19: 10 Maiores litigantes nos processos</caption>
<colgroup>
<col style="width: 62%">
<col style="width: 27%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nome fantasia</th>
<th style="text-align: right;">Número de processos</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(vazio)</td>
<td style="text-align: right;">5368</td>
<td style="text-align: right;">11.02%</td>
</tr>
<tr class="even">
<td style="text-align: left;">CASA CIVIL DO ESTADO DE MATO GROSSO</td>
<td style="text-align: right;">1694</td>
<td style="text-align: right;">3.48%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IBAMA - CPB</td>
<td style="text-align: right;">1464</td>
<td style="text-align: right;">3.01%</td>
</tr>
<tr class="even">
<td style="text-align: left;">NORTE ENERGIA</td>
<td style="text-align: right;">1203</td>
<td style="text-align: right;">2.47%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DEFENSORIA PUBLICA</td>
<td style="text-align: right;">1014</td>
<td style="text-align: right;">2.08%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PROCURADORIA GERAL DO ESTADO</td>
<td style="text-align: right;">885</td>
<td style="text-align: right;">1.82%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ELETROBRAS ELETRONORTE</td>
<td style="text-align: right;">718</td>
<td style="text-align: right;">1.47%</td>
</tr>
<tr class="even">
<td style="text-align: left;">SECRETARIA DE ESTADO DE MEIO AMBIENTE - SEMA</td>
<td style="text-align: right;">441</td>
<td style="text-align: right;">0.91%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GABINETE DO PREFEITO</td>
<td style="text-align: right;">369</td>
<td style="text-align: right;">0.76%</td>
</tr>
<tr class="even">
<td style="text-align: left;">SUPERINTENDENCIA DE ADMINISTRACAO DO MF/ RJ</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.53%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">JIRAU ENERGIA</td>
<td style="text-align: right;">247</td>
<td style="text-align: right;">0.51%</td>
</tr>
<tr class="even">
<td style="text-align: left;">CCBM</td>
<td style="text-align: right;">246</td>
<td style="text-align: right;">0.50%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SECRETARIA DE ESTADO DE FAZENDA - SEFAZ</td>
<td style="text-align: right;">219</td>
<td style="text-align: right;">0.45%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MINISTERIO PUBLICO DO ESTADO DE MATO GROSSO</td>
<td style="text-align: right;">203</td>
<td style="text-align: right;">0.42%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IBAMA SUPERINT REGIONAL NO GOIAS</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">0.40%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-litigantes-ativo">Tabela&nbsp;20</a> mostra os quinze maiores litigantes no polo ativo. Como esperado, figuram entre os maiores litigantes os ministérios públicos e procuradorias.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-litigantes-ativo" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;20: 10 Maiores litigantes nos processos</caption>
<colgroup>
<col style="width: 65%">
<col style="width: 25%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nome fantasia</th>
<th style="text-align: right;">Número de processos</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MINISTERIO PUBLICO DO ESTADO DE MATO GROSSO</td>
<td style="text-align: right;">8168</td>
<td style="text-align: right;">16.77%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PA MP PRG GABINETE DO PROCURADOR GERAL</td>
<td style="text-align: right;">2059</td>
<td style="text-align: right;">4.23%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IBAMA - CPB</td>
<td style="text-align: right;">1940</td>
<td style="text-align: right;">3.98%</td>
</tr>
<tr class="even">
<td style="text-align: left;">AM PROCURADORIA GERAL DA JUSTICA GAB DO PROCURADOR</td>
<td style="text-align: right;">1826</td>
<td style="text-align: right;">3.75%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TO PROCURADORIA GERAL DA JUSTICA</td>
<td style="text-align: right;">1673</td>
<td style="text-align: right;">3.43%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MINISTERIO PUB EST RONDONIA</td>
<td style="text-align: right;">1638</td>
<td style="text-align: right;">3.36%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GABINETE DO PREFEITO</td>
<td style="text-align: right;">1071</td>
<td style="text-align: right;">2.20%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(vazio)</td>
<td style="text-align: right;">1068</td>
<td style="text-align: right;">2.19%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CASA CIVIL DO ESTADO DE MATO GROSSO</td>
<td style="text-align: right;">961</td>
<td style="text-align: right;">1.97%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PROCURADORIA GERAL DA JUSTICA</td>
<td style="text-align: right;">935</td>
<td style="text-align: right;">1.92%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MPEA</td>
<td style="text-align: right;">758</td>
<td style="text-align: right;">1.56%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PROCURADORIA GERAL DO ESTADO</td>
<td style="text-align: right;">749</td>
<td style="text-align: right;">1.54%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TJPA</td>
<td style="text-align: right;">412</td>
<td style="text-align: right;">0.85%</td>
</tr>
<tr class="even">
<td style="text-align: left;">IBAMA SUPERINT REGIONAL NO GOIAS</td>
<td style="text-align: right;">336</td>
<td style="text-align: right;">0.69%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IBAMA/CGFIN - COORDENACAO GERAL DE FINANCAS</td>
<td style="text-align: right;">301</td>
<td style="text-align: right;">0.62%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-cnae">Tabela&nbsp;21</a> mostra as atividades principais das empresas no polo passivo, de acordo com a informação da “Classe” da tabela CNAE. Os casos de “administração pública em geral” provavelmente se referem a diferentes entidades públicas.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cnae" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;21: Quantidade de partes-processos por tipo de atividade.</caption>
<colgroup>
<col style="width: 86%">
<col style="width: 5%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo de atividade</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Administração pública em geral</td>
<td style="text-align: right;">6675</td>
<td style="text-align: right;">13.70%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Geração de energia elétrica</td>
<td style="text-align: right;">3345</td>
<td style="text-align: right;">6.87%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Metalurgia do alumínio e suas ligas</td>
<td style="text-align: right;">1847</td>
<td style="text-align: right;">3.79%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desdobramento de madeira</td>
<td style="text-align: right;">1691</td>
<td style="text-align: right;">3.47%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Justiça</td>
<td style="text-align: right;">1189</td>
<td style="text-align: right;">2.44%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Comércio varejista de ferragens madeira e materiais de construção</td>
<td style="text-align: right;">493</td>
<td style="text-align: right;">1.01%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transporte rodoviário de carga</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">0.60%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Construção de edifícios</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">0.55%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Obras para geração e distribuição de energia elétrica e para telecomunicações</td>
<td style="text-align: right;">261</td>
<td style="text-align: right;">0.54%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Comércio atacadista de madeira e produtos derivados</td>
<td style="text-align: right;">242</td>
<td style="text-align: right;">0.50%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="datajud-2" class="level3">
<h3 class="anchored" data-anchor-id="datajud-2">DataJud</h3>
<p>A base do DataJud não disponibiliza nome nem CNPJ das partes, o que impossibilita análises sobre perfil das partes.</p>
</section>
<section id="trf1-2" class="level3">
<h3 class="anchored" data-anchor-id="trf1-2">TRF1</h3>
<p>A base do TRF1 não disponibiliza o CNPJ das partes, o que impossibilita a realização de análises mais aprofundadas. A única análise feita foi dos maiores litigantes no polo passivo, listados na <a href="#tbl-litigantes-trf1">Tabela&nbsp;22</a>. As formas de participação para determinar as partes no polo passivo foram: “réu”, “requerido”, “executado” e “impetrado”. Os nomes passaram por um processo de padronização, mas ainda podem estar com problemas de taxonomia.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-litigantes-trf1" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;22: Lista dos maiores litigantes no polo passivo, no TRF1 (base grande).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Nome</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IBAMA</td>
<td style="text-align: right;">741</td>
<td style="text-align: right;">17.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">INSS</td>
<td style="text-align: right;">513</td>
<td style="text-align: right;">11.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UNIAO</td>
<td style="text-align: right;">437</td>
<td style="text-align: right;">10.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">INCRA</td>
<td style="text-align: right;">143</td>
<td style="text-align: right;">3.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FUNAI</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">2.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">UNIVERSIDADE FEDERAL DO OESTE DO PARA</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">0.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CAIXA ECONOMICA FEDERAL</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">DEPARTAMENTO NACIONAL DE PRODUCAO MINERAL DNPM</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">2318</td>
<td style="text-align: right;">53.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-litigantes-trf1-ativo">Tabela&nbsp;23</a> mostra os maiores litigantes no polo ativo. As formas de participação para determinar as partes no polo ativo foram: “autor”, “requerente”, “exequente” e “impetrante”. Os nomes passaram por um processo de padronização, mas ainda podem estar com problemas de taxonomia.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-litigantes-trf1-ativo" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;23: Lista dos maiores litigantes no polo ativo, no TRF1 (base grande).</caption>
<colgroup>
<col style="width: 84%">
<col style="width: 7%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nome</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MINISTERIO PUBLICO FEDERAL</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">8.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">IBAMA</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">5.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UNIAO</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">4.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">DEPARTAMENTO NACIONAL DE PRODUCAO MINERAL DNPM</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">2.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGENCIA NACIONAL DE MINERACAO</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">1.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">CAIXA ECONOMICA FEDERAL</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">1.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DEPARTAMENTO NACIONAL DE INFRAESTRUTURA DE TRANSPORTES DNIT</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">INCRA</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">2401</td>
<td style="text-align: right;">75.5%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="discussão-1" class="level3">
<h3 class="anchored" data-anchor-id="discussão-1">Discussão</h3>
<p>A análise do SireneJud indica que empresas de energia são as mais comuns em processos de crime ambiental na região. Já a análise do DataJud não foi possível. Por fim, a análise do TRF1 mostra majoritariamente a União e órgãos como IBAMA, INCRA e FUNAI no polo passivo.</p>
</section>
</section>
<section id="questão-5" class="level2">
<h2 class="anchored" data-anchor-id="questão-5">Questão 5</h2>
<p><strong>Questão</strong>: Existem padrões identificáveis nos casos judicializados quanto às circunstâncias, características dos autores, modalidades e tipos de crimes ambientais?</p>
<section id="discussão-2" class="level3">
<h3 class="anchored" data-anchor-id="discussão-2">Discussão</h3>
<p>Esta questão foi discutida nas análises das questões 1 e 2.</p>
</section>
</section>
<section id="questão-8" class="level2">
<h2 class="anchored" data-anchor-id="questão-8">Questão 8</h2>
<p><strong>Questão</strong>: Quais os principais segmentos econômicos ou grupos empresariais que estão envolvidos na cadeia de produção que tenha alguma relação com crime ambiental (indústria de equipamentos pesados, maquinário agrícola, maquinário de mineração, táxi aéreo, bancos e instituições financeiras de fomento agrícola, leasing)?</p>
<section id="discussão-3" class="level3">
<h3 class="anchored" data-anchor-id="discussão-3">Discussão</h3>
<p>Esta questão foi discutida na análise da questão 2. A <a href="#tbl-cnae">Tabela&nbsp;21</a> mostra que os tipos empresariais mais comuns no polo passivo são empresas de energia, metalurgia e desdobramento de madeira, além de comércio de ferragens e transporte de carga.</p>
</section>
</section>
<section id="questão-12" class="level2">
<h2 class="anchored" data-anchor-id="questão-12">Questão 12</h2>
<p><strong>Questão</strong>: Há correlação entre a incidência de crimes contra a vida ou ameaça em regiões de alta ocorrência de desmatamento, ou mineração ilegal ou crimes ambientais em geral?</p>
<p>Uma possibilidade de análise é comparar índices de homicídios pela população do município com a litigiosidade do município. Para isso, vamos utilizar dados do Sistema Nacional de Informações de Segurança Pública, Prisionais, de Rastreabilidade de Armas e Munições, de Material Genético, de Digitais e de Drogas (SINESP).</p>
<p>O SINESP por município mostra somente as informações de homicídios dolosos. Ou seja, a base não envolve casos de ameaça. Consideramos o ano de 2021 como referência, que é o ano mais recente com informações completas. A taxa de criminalidade do município foi calculada fazendo-se a razão do número de vítimas por habitante, utilizando os dados de população do Censo de 2010.</p>
<section id="sirenejud-3" class="level3">
<h3 class="anchored" data-anchor-id="sirenejud-3">SireneJud</h3>
<p>A <a href="#fig-dispersao-crim-sirenejud">Figura&nbsp;7</a> mostra um gráfico de dispersão da taxa de criminalidade comparada com a litigiosidade dos municípios, considerando a base do SireneJud como fonte. Aparentemente, não existe uma relação clara entre as duas quantidades.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dispersao-crim-sirenejud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-dispersao-crim-sirenejud-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;7: Gráfico de dispersão da taxa de homicídios e litigiosidade.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="datajud-3" class="level3">
<h3 class="anchored" data-anchor-id="datajud-3">DataJud</h3>
<p>A <a href="#fig-dispersao-crim-datajud">Figura&nbsp;8</a> mostra um gráfico de dispersão da taxa de criminalidade comparada com a litigiosidade dos municípios, considerando a base do DataJud como fonte. Aparentemente, também não existe uma relação clara entre as duas quantidades.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dispersao-crim-datajud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-dispersao-crim-datajud-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;8: Gráfico de dispersão da taxa de homicídios e litigiosidade.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="trf1-3" class="level3">
<h3 class="anchored" data-anchor-id="trf1-3">TRF1</h3>
<p>O TRF1 não possui informações de município. Seria possível realizar uma análise a partir dos últimos quatro dígitos dos números dos processos, mas seria uma análise muito limitada. Como as outras bases já não mostraram indícios de relação, decidimos por não realizar essa análise.</p>
</section>
<section id="discussão-4" class="level3">
<h3 class="anchored" data-anchor-id="discussão-4">Discussão</h3>
<p>Nas análises realizadas, não foi identificada uma relação entre índice de homicídios e litigiosidade.</p>
</section>
</section>
<section id="questão-14" class="level2">
<h2 class="anchored" data-anchor-id="questão-14">Questão 14</h2>
<p><strong>Questão</strong>: Qual o tempo de duração médio das ações criminais que envolvam a temática ambiental?</p>
<p>Como temos processos em andamento, a forma adequada de analisar os tempos é utilizando análise de sobrevivência <span class="citation" data-cites="colosimoAnaliseSobrevivenciaAplicada2006">(<a href="#ref-colosimoAnaliseSobrevivenciaAplicada2006" role="doc-biblioref">Colosimo e Giolo 2006</a>)</span>. Faremos isso utilizando gráficos descritivos de Kaplan Meier.</p>
<section id="sirenejud-4" class="level3">
<h3 class="anchored" data-anchor-id="sirenejud-4">SireneJud</h3>
<p>O resultado geral é mostrado na <a href="#fig-km">Figura&nbsp;9</a>. Foram retirados tempos maiores de 10 mil dias e tempos menores que zero. A mediana é de aproximadamente 81 meses, ou seja, quase 7 anos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;9: Curva de sobrevivência dos tempos de tramitação dos processos</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-assunto">Figura&nbsp;10</a> mostra a distribuição dos tempos por assunto, considerando os cinco assuntos com maior volume de processos. As curvas são parecidas em forma e apresentam medianas similares.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-assunto" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-assunto-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;10: Curva de sobrevivência dos tempos de tramitação dos processos, por assunto</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-classe">Figura&nbsp;11</a> mostra os tempos por classe processual. A classe com maior tempo mediano é a execução fiscal, com 189 meses, enquanto a classe com menor tempo mediano é o procedimento comum cível, com 26 meses de duração.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-classe" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-classe-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;11: Curva de sobrevivência dos tempos de tramitação dos processos, por classe</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-tribunal">Figura&nbsp;12</a> mostra os tempos por tribunal. Por serem 10 categorias, é um pouco difícil de visualizar todas as curvas. O tribunal com mnor mediana de tempo é o TJRO, com mediana de 43 meses, enquanto o tribunal com maior tempo é o TJMT, com mediana de 100 meses.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `dplyr::mutate()`.
ℹ In argument: `assunto = stringr::str_wrap(sgt_nm_assunto, 20)`.
Caused by warning in `stri_split_lines()`:
! argument is not an atomic vector; coercing</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-km-tribunal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-tribunal-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;12: Curva de sobrevivência dos tempos de tramitação dos processos, por tribunal</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-municipio">Figura&nbsp;13</a> mostra os tempos por município. O município com maior tempo mediano é Altamira, com 130 meses, enquanto o município com menor tempo mediano é Barcarena, com 24 meses de duração.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-municipio" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-municipio-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;13: Curva de sobrevivência dos tempos de tramitação dos processos, por município</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="datajud-4" class="level3">
<h3 class="anchored" data-anchor-id="datajud-4">DataJud</h3>
<p>No DataJud, o tempo foi calculado fazendo-se a diferença entre a data de última baixa e a data do primeiro recebimento. O resultado geral é mostrado na <a href="#fig-km-datajud">Figura&nbsp;14</a>. Foram retirados tempos maiores de 10 mil dias e tempos menores que zero. A mediana é de aproximadamente 37 meses, pouco mais de 3 anos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-datajud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-datajud-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;14: Curva de sobrevivência dos tempos de tramitação dos processos</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-assunto-datajud">Figura&nbsp;15</a> mostra a distribuição dos tempos por assunto, considerando os cinco assuntos com maior volume de processos. O assunto “Quadrilha ou Bando” apresentou o maior tempo, com 50 meses, enquanto tráfico de drogas apresentou tempo similar à categoria “Outros”, com 36 meses.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-assunto-datajud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-assunto-datajud-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;15: Curva de sobrevivência dos tempos de tramitação dos processos, por assunto</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-tribunal-datajud">Figura&nbsp;16</a> mostra os tempos por tribunal. O menor tempo mediano identificado foi no TJRR, com mediana de 5 meses, enquanto o maior tempo foi no TJAM, com mediana de 96 meses.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-tribunal-datajud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-tribunal-datajud-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;16: Curva de sobrevivência dos tempos de tramitação dos processos, por tribunal</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-municipio-datajud">Figura&nbsp;17</a> mostra os tempos por município. O município com maior tempo mediano é Boa Vista, com 5 meses meses, enquanto o município com menor tempo mediano é Manaus, com 85 meses de duração.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-municipio-datajud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-municipio-datajud-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;17: Curva de sobrevivência dos tempos de tramitação dos processos, por município</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="trf1-4" class="level3">
<h3 class="anchored" data-anchor-id="trf1-4">TRF1</h3>
<p>A análise do TRF1 exige um esforço maior no tratamento das movimentações processuais. Para realizar a análise, foram consideradas algumas heurísticas de classificação. Primeiro, o evento de baixa considerado foi o último cuja movimentação apresenta a informação de baixa. O início do processo foi considerado pelo campo <code>data_de_autuacao</code>. Todos os processos foram considerados como baixados, já que a pesquisa realizada para listar os processos é retrospectiva. Nesse caso, a análise de sobrevivência não é necessária, mas foi mantida para não mudar as visualizações</p>
<p>No TRF1, o resultado geral é mostrado na é a <a href="#fig-km-trf1">Figura&nbsp;18</a>. Foram retirados tempos maiores de 10 mil dias e tempos menores que zero. A mediana é de aproximadamente 29 meses, ou 2 anos e meio.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-trf1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-trf1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;18: Curva de sobrevivência dos tempos de tramitação dos processos</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-km-assunto-trf1">Figura&nbsp;19</a> mostra a distribuição dos tempos por assunto, considerando os cinco assuntos com maior volume de processos. Os tempos variam pouco por assunto, sendo que o assunto com menor tempo é “Ambiental” e o assunto com maior tempo é o “Rural Art. 4851”.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-km-assunto-trf1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="2-descritiva_files/figure-html/fig-km-assunto-trf1-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figura&nbsp;19: Curva de sobrevivência dos tempos de tramitação dos processos, por assunto</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="discussão-5" class="level3">
<h3 class="anchored" data-anchor-id="discussão-5">Discussão</h3>
<p>As três bases apresentam padrões de tempos diferentes. No SireneJud, os processos são longos, com duração mediana maior que 7 anos e o tempo dos processos não varia muito por tema. No DataJud, os processos são um pouco mais rápidos (6 anos), com uma variação considerável por assunto. No TRF1, os processos são mais curtos, o que possivelmente é um efeito do método retrospectivo de coleta, e com pouca variação nas medianas por assunto.</p>
</section>
</section>
</section>
<section id="referências" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">Referências</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-colosimoAnaliseSobrevivenciaAplicada2006" class="csl-entry" role="listitem">
Colosimo, Enrico Antonio, e Suely Ruiz Giolo. 2006. <em>Análise de Sobrevivência Aplicada</em>. <span>Editora Blucher</span>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>